[database]
# Support sqlite/mysql/postgres, example: sqlite://data.db or mysql://user:pass@localhost/db
url = sqlite://data.db

[log]
# Log level: error, warn, info, debug, trace
level = info

[mail]
# SMTP server configuration
smtp_server = smtp.example.com
smtp_user = your_email@example.com
smtp_pass = your_password